### ISSUE TITLE
🚀 feat: utilizing a ISR model for GitHub events

### ISSUE THREAD

**Issue by BryanPan342** [uclaacm/opensource#1]
Wanted to share some next.js-isms to help out!

I think some of the info properties you are receiving can be bundled at build time! Build time??? Next.js has this super-nifty feature that I think we have discussed before called [Incremental Static Regeneration](https://blog.logrocket.com/incremental-static-regeneration-with-next-js/)! I think the following code snippet could be obtained on build time, at a revalidation rate of 60s since the data does not have to be instantaneous!

And you get the benefit of amortizing the GET request 😊

https://github.com/uclaacm/opensource/blob/727285e46941e0ce2da78e7b7224907c557efc72/pages/index.tsx#L10-L32

**Comment by mattxwang** [comment]
Oh, great point - I hadn't even thought of that as a use-case for ISR, still getting the hang of Next! I'll look to get it in soon 😊

**Comment by BryanPan342** [comment]
Haha soon all of UCLA will be using next.js muahaha 😈

**Comment by mattxwang** [comment]
I (believe) I was able to implement this in https://github.com/uclaacm/opensource/commit/b4301ee2dcc1c934442a29eb408b52c29ec6e894

> Haha soon all of UCLA will be using next.js muahaha 😈

We can become next ambassadors 😎

**Comment by BryanPan342** [comment]
Looks good king 👑
