### ISSUE TITLE
Write out our `Contribute` page!

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/opensource#11]
The [Contribute page](https://opensource.uclaacm.com/contribute) is currently empty! But, it shouldn't be :) 

Some things we can put on the page:

* what is open-source?
* pointers to git, GitHub
* an example walkthrough of how to fork, clone, add, commit, push, and open a PR
* a list of projects where it's easy to start contributing with; bonus points if we can filter to issues tagged with "good first issue" or "help wanted" like [good first issue](https://goodfirstissue.dev/) does!

**Comment by jainsujay02** [comment]
The contribution page is up, thanks to Matt Nieva!
