### ISSUE TITLE
Add timestamps / "moments" to our GitHub live feed

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/opensource#15]
The GitHub Events API provides us the time that an event happens, but we don't do anything with it. I'd love to see us render this somewhere on the [live feed](https://opensource.uclaacm.com) somewhere!

To do this, you'll need to do a couple of things:

1. First, determine how you want to show time passing. I personally like [Moment.js's "From Now" functionality](https://momentjs.com/docs/#/displaying/fromnow/), though Moment itself is likely overkill for what we're looking to do.
2. Then, adjust the logic in either `GitHubEvent` or `GitHubEventAction` to make use of the `created_at` field in the [GitHub Events object](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads); make sure you're using the right one! You can see examples in the dump of the [REST Endpoint that we hit](https://api.github.com/orgs/uclaacm/events)
3. Then, apply whatever feature you described in the first step.
4. Finally, render this to the individual `<GitHubEvent />`. You may want to consider adding some sort of two-column or `float: right;`-esque behaviour to keep everything rather compact.

**Comment by logicalahara** [comment]
hey @mattxwang, I'd like to contribute to this issue. any prerequisites ?

**Comment by mattxwang** [comment]
Looks like this is abandoned; @reginawang3495 feel free to assign.

**Comment by JackTheVac** [comment]
Added Time Stamp to GitHub Event Live feed
