### ISSUE TITLE
Cyber Aliasing Issue 

### ISSUE THREAD

**Issue by jainsujay02** [uclaacm/opensource#151]
Cyber seems to Alias with just cyber instead of cyber-acm. This is causing their logo to not be displayed. This should be an easy fix/adding an additional name with the logo.

**Comment by ansh-saini** [comment]
Hello, I would like to work on this. Can you assign it to me?

**Comment by jainsujay02** [comment]
Hey @ansh-saini,  cc'ing ACM's Dev Team Director @snigdha-kansal as I'm now an advisor.

**Comment by snigdha-kansal** [comment]
Thanks for cc'ing, just assigned! And thanks for picking it up

**Comment by ansh-saini** [comment]
Hi @jainsujay02 Can you help me pinpoint the exact issue? I'm unable to find where the logo is not getting displayed 😅

**Comment by jainsujay02** [comment]
<img width="603" alt="image" src="https://github.com/user-attachments/assets/895fc53d-50d5-4a06-8706-7e7ad4a92dbb">

There was probably some kind of update/change since this ticket was created causing the open source website to now show the ACM logo instead of the ACM Cyber logo. This is just one example. You'll need to find the issue in the code yourself. 

CC: @snigdha-kansal
