### ISSUE TITLE
Update Navigation 

### ISSUE THREAD

**Issue by jainsujay02** [uclaacm/opensource#152]
The open-source site was originally intended to be a stand-alone website. However, we would now like to keep it linked to ACM's main website. This naturally causes a weird navigation experience with no way to navigate back to the main ACM website from the open-source website. 

To address think, I can think of two approaches: 

1. We add a back to the main site button on the home page (which is a little cringe) but acceptable for our purposes. 
2. We modify the navigation bar so that it includes links to our main website. 

Ideally, you'd experiment with both of these and see which feels more intuitive from a user's perspective.

**Comment by ansh-saini** [comment]
Hi. I would like to work on this. Can I take this up?

I think it'd be best to modify the navbar to include a link to the main website. I can think of two ways of doing this:

1. We can change the link of the top left logo to the main website.
    <img width="1800" alt="image" src="https://github.com/uclaacm/opensource/assets/32511936/cb6dce37-1b70-4191-9705-c3d9ce1a7c70">
2. Adding a 'home' link in the links section
    <img width="1800" alt="image" src="https://github.com/uclaacm/opensource/assets/32511936/63816e2f-816c-40bb-94f3-9ae0d46b1135">

**Comment by jainsujay02** [comment]
Hey Ansh,

Thank you for helping out! I've assigned the ticket to you. Let me know if
you've any questions. Otherwise, when you're done, please request me or
Arsh Malik as your reviewer.

**Comment by ansh-saini** [comment]
Hi @jainsujay02.
I mentioned two ways of solving this problem in my previous comment. Would really like to know your thoughts on which one I should implement.

**Comment by jainsujay02** [comment]
Hey Ansh,

Ah my bad, I forgot to reply to that part of your message. I prefer option
2.

**Comment by ArshMalik02** [comment]
I had some thoughts to add. Intuitively, I feel like we should go with option 1 i.e. the logo in the navigation bar should be consistent with the main website since we now have open source in the main website's navigation bar and it should link to the main website's landing page. Thoughts @matthewcn56 ?

**Comment by ArshMalik02** [comment]
Closed with #157
