### ISSUE TITLE
Bug: Unresponsive Projects Page

### ISSUE THREAD

**Issue by snigdha-kansal** [uclaacm/opensource#202]
## Issue 
The [Projects Page](https://opensource.uclaacm.com/projects) is currently not responsive on mobile view. The CSS layout becomes distorted causing elements to not display properly as shown below:

<img width="200" alt="image" src="https://github.com/user-attachments/assets/3ab12301-6bc1-409c-b67e-362ee4ce3a1d">
<>
<img width="200" alt="image" src="https://github.com/user-attachments/assets/375e243a-46af-4479-ac1f-8e824ac87c77">

## Proposed Solution
Implement responsive design using flexible units (e.g., %, vw, rem) and media queries to ensure the layout adapts to smaller screen sizes. Utilize Flexbox or CSS Grid to maintain proper element alignment and prevent overflow across all devices.

The projects should be laid out in a style similar to how it's done for the mobile view of [Team Page](https://www.uclaacm.com/officers) on the ACM @ UCLA Website.

A good resource to refer to would be the [intern training](https://github.com/uclaacm/centralized-intern-training).

**Comment by ansh-saini** [comment]
Hi, can I work on this?
