### ISSUE TITLE
Bug: Unresponsive Main Page

### ISSUE THREAD

**Issue by snigdha-kansal** [uclaacm/opensource#203]
## Issue 
The [Main Page](https://opensource.uclaacm.com/) is currently not responsive on mobile view. The CSS layout becomes distorted causing elements to not display properly as shown below:

<img width="200" alt="image" src="https://github.com/user-attachments/assets/7464d7b2-4cc3-456f-9c89-49f0ead55fc9">
<>
<img width="200" alt="image" src="https://github.com/user-attachments/assets/74386ca0-c881-4903-a5f4-abf35a30c7bb">

## Proposed Solution
Implement responsive design using flexible units (e.g., %, vw, rem) and media queries to ensure the layout adapts to smaller screen sizes. Utilize Flexbox or CSS Grid to maintain proper element alignment and prevent overflow across all devices.

**Comment by ansh-saini** [comment]
Hi, can I work on this?

**Comment by ansh-saini** [comment]
Hello @snigdha-kansal 
Can I work on this?

**Comment by snigdha-kansal** [comment]
Hey @ansh-saini! I'm really sorry but one of our Dev officers, @cweihan01, is already working on this issue.
Would you be interested in taking on #96 instead? :)

**Comment by ansh-saini** [comment]
Sure!

**Comment by cweihan01** [comment]
Hi @ansh-saini, I'm in the midst of working on this, perhaps you could look into another issue? Thanks!
