### ISSUE TITLE
Process `WatchEvent` properly

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/opensource#21]
The `WatchEvent` occurs when someone watches our repository. This isn't too frequent, but it's also not uncommon. Thus, I'd like to display this properly on [the live feed](https://opensource.uclaacm.com/).

To resolve this, you'll need to:

1. Inspect the structure of a `WatchEvent`; see the [Watch Event](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#watch), and the dump of the [REST Endpoint that we hit](https://api.github.com/orgs/uclaacm/events)
2. Add a `case` statement for `WatchEvent` in `GitHubEventAction.tsx`
3. Process the relevant parameters for the statement that we'd like to generate. I would like to see something like:

```
@mattxwang watched uclaacm/website
```

This should be only a couple of lines of code!

See #10 for a related issue and resolving PR!

## Artifacts / Relevant Pointers

The relevant file is here:

https://github.com/uclaacm/opensource/blob/7c44795e44d802be8422e79b7ba42f8ab42f8398/components/GitHubEventAction.tsx#L12

Here's a dump of a watch event:

```json
{
    "id": "18489173025",
    "type": "WatchEvent",
    "actor": {
      "id": 68075820,
      "login": "isabellegoralsky",
      "display_login": "isabellegoralsky",
      "gravatar_id": "",
      "url": "https://api.github.com/users/isabellegoralsky",
      "avatar_url": "https://avatars.githubusercontent.com/u/68075820?"
    },
    "repo": {
      "id": 342777648,
      "name": "uclaacm/design-website",
      "url": "https://api.github.com/repos/uclaacm/design-website"
    },
    "payload": {
      "action": "started"
    },
    "public": true,
    "created_at": "2021-10-18T21:10:37Z",
    "org": {
      "id": 8324381,
      "login": "uclaacm",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/uclaacm",
      "avatar_url": "https://avatars.githubusercontent.com/u/8324381?"
    }
  },
```

**Comment by bhavishya-s** [comment]
Hey, I'd like to take this

**Comment by mattxwang** [comment]
> Hey, I'd like to take this

Go for it!
