### ISSUE TITLE
feat: *actually* random featured project

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/opensource#30]
Currently, the **featured project** section on the [homepage](https://opensource.uclaacm.com/) is hard-coded to Buffer Buffet. It would be great if this was randomly picked on page load instead! We can pick a project from [`data/projects.ts`](https://github.com/uclaacm/opensource/blob/main/data/projects.ts).

**Comment by mattxwang** [comment]
@reginawang3495

**Comment by NetanelK** [comment]
I can do it

**Comment by reginawang3495** [comment]
Hi @NetanelK these are reserved, hope you can find a better one somewhere else!! I'll put a reserved tag on the ones that we are keeping :) 

Sorry for the inconvenience!

**Comment by reginawang3495** [comment]
closed by #33
