### ISSUE TITLE
feat: add SEO w/ `next-seo` 

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/opensource#31]
Currently, when you send someone a link to this website, there's not much metadata, or page-specific information. Here's an example on Discord:

![Screen Shot 2021-11-15 at 9 26 45 PM](https://user-images.githubusercontent.com/14893287/141926211-8364cfe9-f8bb-489d-8976-f86d3a1675b0.png)

I want to add some SEO-related metadata to our site so that it renders properly on link share, like this:

![Screen Shot 2021-11-15 at 9 27 29 PM](https://user-images.githubusercontent.com/14893287/141926276-36616ff1-c71d-407d-bed1-75e76f5a8f7a.png)

To do that, I think we should install [`next-seo`](https://github.com/garmeeh/next-seo), and then do some of the base configuration. For now, using the ACM logo as the image (with the right dimensions) should suffice; the body copy for each page can be a simple one-liner (feel free to use what's on the home page right now).

This can be a bit tricky; if you're curious, you can look at:

* a similar PR I made on the `uclaacm/website` repo: https://github.com/uclaacm/website/pull/244
* a longer writeup where I provide more context: https://github.com/uclaacm/website/issues/116

**Comment by mattxwang** [comment]
@reginawang3495

**Comment by ArushRam** [comment]
> Currently, when you send someone a link to this website, there's not much metadata, or page-specific information. Here's an example on Discord:
> 
> ![Screen Shot 2021-11-15 at 9 26 45 PM](https://user-images.githubusercontent.com/14893287/141926211-8364cfe9-f8bb-489d-8976-f86d3a1675b0.png)
> 
> I want to add some SEO-related metadata to our site so that it renders properly on link share, like this:
> 
> ![Screen Shot 2021-11-15 at 9 27 29 PM](https://user-images.githubusercontent.com/14893287/141926276-36616ff1-c71d-407d-bed1-75e76f5a8f7a.png)
> 
> To do that, I think we should install [`next-seo`](https://github.com/garmeeh/next-seo), and then do some of the base configuration. For now, using the ACM logo as the image (with the right dimensions) should suffice; the body copy for each page can be a simple one-liner (feel free to use what's on the home page right now).
> 
> This can be a bit tricky; if you're curious, you can look at:
> 
> * a similar PR I made on the `uclaacm/website` repo: [per-page SEO (meta tags, opengraph) via `next-seo` website#244](https://github.com/uclaacm/website/pull/244)
> * a longer writeup where I provide more context: [Populate page metadata, social media metadata website#116](https://github.com/uclaacm/website/issues/116)

**Comment by mattxwang** [comment]
Closed by #76.
